### ISSUE TITLE
Temperature not logged correctly

### ISSUE THREAD

**Issue by harold65** [harold65/SolarMeter#1]
When using buienradar as source for temperature, the value is not correctly read.

**Comment by FunnyAnimal** [comment]
I think this is related to the issue i just submitted, https://github.com/harold65/SolarMeter/issues/3 .

**Comment by harold65** [comment]
The issue is not the value itself but the fact that the arduino is too slow to scan the >50K xml data returned from xml.buienradar.nl
Older Arduino versions have a faster (but less reliable) Find() function that will work ok.

**Comment by FunnyAnimal** [comment]
What exactly do you mean with "Older Arduino versions" ? Older IDE?

I am using IDE version 1.8.3 and it works fine. (My Arduino UNO board is from May 2013.)

I use the following code in Temperature.cpp, it has been working fine now for over a year:

```
void Temperature::GetTemperature()
{
    // Get temperature from buienradar
    EthernetClient buienradarClient;

    int res = 0;
    int retries = 5;
    while (retries-- > 0 && res != 1)
    {
      res = buienradarClient.connect((char*)"xml.buienradar.nl",80);
      if (retries > 0 && res != 1) delay(561);  // Arbitrary delay
    }
    if(res == 1) // connection successfull
    {
        buienradarClient << F("GET / HTTP/1.1") << endl;
        buienradarClient << F("Host: xml.buienradar.nl") << endl << endl;

        retries = 50; // Wait maximally 50 * 0.05 = 2.5 seconds
        while(retries-- > 0
            && buienradarClient.connected()
            && ! buienradarClient.find((char*)weatherStation))
        {
            delay(50);
        } // while

        if (retries > 0)
        {
            if(buienradarClient.find((char*)"<temperatuurGC>"))
            {
                actual = buienradarClient.parseFloat();
                // Calculate new average
                average = (todayCnt * average) + actual;
                todayCnt++;
                average /= todayCnt;
            }
        }
        buienradarClient.stop();
    }
}
```

**Comment by harold65** [comment]
please read this post and the following:
https://www.wijhebbenzon.nl/index.php/19-monitoren-loggen-en-meten/5410-solarmeter-v11-43?start=66#11255
Depending on hardware and ide version we get different results.

**Comment by FunnyAnimal** [comment]
Yes, the retrieving can take quite long. But i don't care about that; for me it is important that it works and is reliable. The code I posted above works very reliable for me.
